apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-config"
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}-config"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
data:
  # Add your environment variables from docker-compose.env here
  # For production, sensitive values should use Kubernetes secrets instead
  PAPERLESS_TIME_ZONE: "UTC"
  PAPERLESS_CONSUMER_POLLING: "60"
  PAPERLESS_OCR_LANGUAGE: "eng"
