{{- if .Values.gotenberg.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-gotenberg
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-gotenberg
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}-gotenberg
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}